dataset_path: certificados-personas-por-fecha-ingreso-provincia-localidad.csv
results_dir: results
model:
  hidden_layer_sizes: [50]
  activation: relu
  alpha: 0.0001
  max_iter: 300
  random_state: 42
train:
  test_size: 0.2
  random_state: 42
